# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Fast FTP
      # You may pin to the exact commit or the version.
      # uses: anvil-solutions/Fast-FTP-Action@de62eeaf1c409a96c7304f3bba8bf8194d0fa98f
      uses: anvil-solutions/Fast-FTP-Action@2.1.3
      with:
        # FTP server name (you may need to specify a port)
        server: planner.alexsol.is
        # FTP account username
        username: ${secrets.FTP_USERNAME}
        # FTP account password
        password: ${secrets.FTP_PASSWORD}
        # Protocol used to deploy (ftp or sftp)
        # method: # optional, default is ftp
        # The local folder to copy, defaults to root project folder
        local_dir: ./build
        # The remote folder to copy to, deafults to root FTP folder
        remote_dir: / # optional, default is .
    
